#!/usr/bin/env python

import sys
import os
import argparse
import json

class ProjectSetup():

    def __init__(self):
	here = str(os.path.dirname(os.path.realpath(__file__)))
	config = os.path.join(here,'config.json')

	self.project_types = ['ftr','shr','tlr','tvc']
	self.destination = None

	self.args = self._parser(config)

	self.destination = self._processArgs(self.args, self.project_types)
	self.paths = self._getProjectPaths(config, self.args.type, self.destination)

	self._createProject(self.paths)

	self._touchProjectFile(self.destination)

    def _dirtyString(self,string):
	# only allow lowercase and underscore
	clean_string_verification = 'abcdefghijklmnopqrstuvwxyz_0123456789'
	clean_string = ''.join([x for x in string if x in clean_string_verification])
	# check for uppercase letters
	if string.isupper() or not (string.isupper() or string.islower()):
	    return 1
	elif len(clean_string) != len(string):
	    return 2
	else:
	    return False

    def _parser(self,config):
	parser = argparse.ArgumentParser(prog='scnprojectsetup',
					 description='A sript that creates project folders based on a config file.',
					 usage='scnprojectsetup name type destination [-h] [-v] [-c FILE]\n'+\
					     'example: scnprojectsetup lhs03e01 ftr /Volumes/scn_ftr_04')
	parser.add_argument("name",help="Project name")
	parser.add_argument("type",help=("Project type: " + ' '.join(self.project_types)))
	parser.add_argument("destination",help="Specify the destination folder",
			    metavar='FOLDER')
	parser.add_argument("-v","--verbose",help='Increase output verbosity',
			    action="store_true")
	parser.add_argument("-c","--config",help='Specify a custom config file',
			    default=config,
			    metavar='FILE')
	if len(sys.argv) == 4:
	    args = parser.parse_args()
	else:
	    print 'scnprojectsetup: error: too few arguments\n'
	    parser.print_help()
	    sys.exit(0)

	return args

    def _processArgs(self,args,project_types):
	project_type = args.type
	project_name = args.name
	verbose = args.verbose
	destination_root = args.destination

	# -------------------- #
	# process project_type
	# -------------------- #
	if project_type in project_types:
	    project_type = project_type
	else:
	    try:
		project_type = int(project_type)
		project_type = project_types[project_type]
	    except:
		sys.exit(args.type + ' is not a recognised project type' +\
                             '\nRecognized types: %s' % ' '.join(self.project_types))
	if verbose:
	    print 'PROJECT TYPE: %s' % project_type

	# -------------------- #
	# process project_name
	# -------------------- #
	if self._dirtyString(project_name):
	    if self._dirtyString(project_name) == 2:
		sys.exit("Project name contains non-ascii characters." \
			 "\nThis is not according to specification. Project creation cancelled.")
	    else:
		sys.exit("Project name contains UPPERCASE letters."\
			 "\nThis is not according to specification. Project creation cancelled.")

	if verbose:
	    print 'CONFIG FILE: %s' % args.config

	destination = os.path.join(destination_root,project_name)
	if verbose:
	    print 'DESTINATION DIR: %s' % destination

	return destination

    def _getProjectPaths(self,project_folders_cfg,path_type,path_root):
	# load the config file
	json_data = open(project_folders_cfg)
	folder_cfg = json.load(json_data)
	json_data.close()

	# config file list definitions
	pathstring = 0

	# parse the config file
	paths = folder_cfg['project']
	paths.extend(folder_cfg[path_type])


	project_paths = []
	for path in paths:
	    project_paths.append(os.path.join(path_root,path_type,path[pathstring]))

	# return all paths to be created as a list of strings
	return project_paths

    def _createProject(self,paths):
	for path in paths:
	    try:
		os.makedirs(path)
	    except OSError as e:
		existing_folder = os.path.join(self.destination,self.args.type)
		sys.exit("%s already exists" % existing_folder)

    def _touchProjectFile(self,destination):
	project_file = os.path.join(destination,(self.args.name + '.txt'))
	open(project_file, 'a').close()

if __name__ == '__main__':
    scnprojectsetup = ProjectSetup()
